AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*.rb
    - bin/bundle
    - bin/delayed_job
    - bin/rails
    - bin/rake
    - bin/rspec
    - bin/setup
    - bin/spring
    - bin/update
    - bin/webpack
    - bin/webpack-dev-server
    - bin/yarn
    - "node_modules/**/*"
    - "vendor/**/*"
    - "*.gemspec"
  TargetRubyVersion: 2.6

Bundler/OrderedGems:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 1000

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Max: 200

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/RedundantPercentQ:
  Enabled: false
